### ISSUE TITLE
Speed of confetti depends on monitor. 

### ISSUE THREAD

**Issue by slowSort** [alampros/react-confetti#117]
Hi there, I've noticed an interesting behaviour with react-confetti, which I think may be a bug. Depending on the monitor I use, the confetti falls at a different speed. I think this is due to the refresh rate.

Regular macbook pro monitor:
https://user-images.githubusercontent.com/35369732/128694392-9bc86f13-67de-41aa-9f9c-8a7dd7b3a32e.mp4

Intehill 240HZ Monitor
https://user-images.githubusercontent.com/35369732/128694680-86b72cb9-732d-4f15-8ed8-7f1a7edbf295.mp4

If there's any helpful information I can include about this issue let me know, and I can add it! 😃

**Comment by alampros** [comment]
Thanks for the report!

That sounds about right, since we're relying on the `requestAnimationFrame` API to provide the timing. The RAF API is definitely the right tool for the job, but I don't believe it provides any means of throttling the frame rate. We'd have to build in a manual fps counter and logic – which I would gladly accept a PR for!

**Comment by timothyerwin** [comment]
@slowSort @alampros I'm seeing the same problem. It's really nice on desktop but speeds up too much on mobile...I think there are some methods for framerate around the web...

https://stackoverflow.com/questions/19764018/controlling-fps-with-requestanimationframe

**Comment by timothyerwin** [comment]
@alampros maybe use above and add `framerate={}` property?

**Comment by piotr-cz** [comment]
This behavior (speed on high refresh-rate screens) is described in MDN > [requestAnimationFrame() method](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)
