### ISSUE TITLE
Doesn't support react@18.1.0

### ISSUE THREAD

**Issue by alisonqiu** [alampros/react-confetti#131]
I couldn't install because React is unable to resolve dependency tree as my current version of React is not supported. Can it be updated to be used on react@18.1.0?

full error:
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: wordle@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0 || ^17.0.1" from react-confetti@6.0.1
npm ERR! node_modules/react-confetti
npm ERR!   react-confetti@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/alisonqiu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alisonqiu/.npm/_logs/2022-05-10T20_00_57_148Z-debug-0.log`

**Comment by carolinapowers** [comment]
I'm dealing with the same issue ` ERROR  react-confetti@6.0.1 requires a peer of react@^16.3.0 || ^17.0.1 but version 18.1.0 was installed.` . Would really really appreciate if @alampros merged [#132](https://github.com/alampros/react-confetti/pull/132) since it's the only dependency we have left that hasn't upgraded yet and is keeping us from upgrading to React 18. Thank you!
