### ISSUE TITLE
componentWillReceiveProps has been renamed - Warning

### ISSUE THREAD

**Issue by gaagai** [alampros/react-confetti#69]
???

**Comment by wheeler** [comment]
@gaagai you are seeing this warning because you are using React 16.9 or higher which has warnings about lifecycle methods that are deprecated. This package uses one of those lifecycle methods.

https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#renaming-unsafe-lifecycle-methods

I've created PR #70 to resolve.

**Comment by alampros** [comment]
Resolve by #70 - thanks @wheeler !
