### ISSUE TITLE
Error: Super expression must either be null or a function

### ISSUE THREAD

**Issue by mheisig** [alampros/react-confetti#76]
I'm having the same issue someone else reported here: [Stackoverflow](https://stackoverflow.com/questions/58823451/react-confetti-super-expression-must-either-be-null-or-a-function)

This is in a Next.js project and there are no problems when running in local development. This only happens when the production build is created so I'm not sure if something in the minification process is causing the problem?

Downgrading to 4.0.1 appears to resolve the issue.

Dependencies:
```
    "react": "^16.9.0",
    "react-confetti": "4.0.1",
    "react-dom": "^16.10.2",
```

**Comment by florianmartens** [comment]
Same issue here. Thank you for opening up the issue.

**Comment by alampros** [comment]
Thanks for reporting this issue! I'll take a look at it tomorrow.

**Comment by cjmyles** [comment]
@alampros any luck with this?

**Comment by svechinsky** [comment]
The same issue with me, the downgrading solution worked.

**Comment by cjmyles** [comment]
@svechinsky Can you paste your code - I'm struggling to determine what props are allowed on that version of Confetti. Ideally the latest version would work in production.

**Comment by svechinsky** [comment]
Here is what I had 
```
<Confetti numberOfPieces={333} recycle={false} />
```
At least as of 6 days ago this didn't work in production with the latest version but did work locally. Downgrading fixed the production issue.

**Comment by cjmyles** [comment]
@svechinsky I'm using Typescript so it files on compilation, as apparently I need a `canvasRef` property.

**Comment by cjmyles** [comment]
@alampros Would be amazing if you could fix the issue with the latest version in production.

**Comment by stolinski** [comment]
I'm also hitting this same error in production.  `0.5.1`. Downgraded to 0.4.1 fixe the issue.

**Comment by hvlmnns** [comment]
> I'm also hitting this same error in production. `0.5.1`. Downgraded to 0.4.1 fixe the issue.
>>> `5.0.1`. Downgraded to 4.0.1

**Comment by roelvan** [comment]
Same here, downgrading to `4.0.1` does the trick for now.

**Comment by Mesoptier** [comment]
This is still an issue for me. I'm trying to figure out a fix. Some notes:
- The issue only occurs if I do a Webpack build of my application with `--mode=production` and the devtool option disabled. It does not occur if I run with `--mode=development` or with devtool option enabled (possibly only if set to an "*-eval" value).
- The issue does not occur when I explicitly import the unminified version. That is `import Confetti from 'react-confetti/dist/react-confetti';` instead of `import Confetti from 'react-confetti';` so it seems to me there is something awry with the minification step.

**Comment by Mesoptier** [comment]
I have cloned this project's repository and ran the `build` myself. Now I have the `react-confetti.min.js`  (red in diff) that was installed before using `yarn add react-confetti` in my application and the `react-confetti.min.js` (green in diff) that I just built. I ran prettier on both files to get a cleaner diff. I then diffed the files and got the following result:

```diff
@@ -892,14 +892,6 @@
                         if (Array.isArray(t)) return t;
                     })(t) ||
                     (function(t, e) {
-                        if (
-                            !(
-                                Symbol.iterator in Object(t) ||
-                                '[object Arguments]' ===
-                                    Object.prototype.toString.call(t)
-                            )
-                        )
-                            return;
                         var n = [],
                             r = !0,
                             i = !1,
@@ -1025,7 +1017,7 @@
                                 },
                             })),
                                 e && D(t, e);
-                        })(e, t),
+                        })(e, o['Component']),
                         (n = e),
                         (r = [
                             {
@@ -1091,7 +1083,7 @@
                         i && I(n, i),
                         e
                     );
-                })(o.Component);
+                })();
             function A(t) {
                 var e = {},
                     n = {},

```

As you can see there is some funny business going on with passing `o.Component` to some function. This is what causes the `Super expression...` error, since the function is being passed `undefined` instead of the Component constructor. 

When I include the minified script that I just built instead of the one that is installed I no longer get the error, so it appears this is indeed the root cause.

**Comment by Mesoptier** [comment]
@alampros It seems that something has gone wrong in the build process when the `5.0.1` version was published to npm. When I run the `build` command in the react-confetti repository on my machine it produces a different minified script than the one that is provided when installing the package. 

Perhaps a solution is to simply try publishing the package again? Making sure that the correct minified file is generated.

**Comment by Mesoptier** [comment]
Yeah, this is still relevant!

@alampros Could you look into what I posted above?

**Comment by rkuykendall** [comment]
@alampros Are you even here or do we need to fork this?

**Comment by rkuykendall** [comment]
Good point stale bot. Forked the project here, overhauled the build/publication process and actively accepting PRs:

https://github.com/rkuykendall/confetti-react
